import { createSlice } from "@reduxjs/toolkit";

export const rotateSlice = createSlice({
  name: "rotate",
  initialState: {
    plots: [
      {
        name: "Cuccurbites et crucifères primeurs",
        length: 585,
        beds: {
          first: [
            { name: "Brocoli", length: 3 },
            { name: "Bok choy", length: 1 },
            { name: "Chou-rave", length: 1 },
            { name: "Kale", length: 1 },
            { name: "Brocoli", length: 5 },
            { name: "Courgette", length: 3 },
            { name: "Chou-fleur", length: 2 },
          ],
          last: [{ name: "Engrais vert", length: 16 }],
        },
      },
      {
        name: "Verdures-racines",
        length: 585,
        beds: {
          first: [
            { name: "Mesclun", length: 2 },
            { name: "Pois", length: 4 },
            { name: "Carotte", length: 2 },
            { name: "Betterave", length: 1 },
            { name: "Navet", length: 1 },
            { name: "Épinard", length: 1 },
            { name: "Mesclun", length: 2 },
            { name: "Épinard", length: 3 },
          ],
          last: [
            { name: "Betterave", length: 2 },
            { name: "Mesclun", length: 8 },
            { name: "Carotte", length: 3 },
            { name: "Mesclun", length: 3 },
          ],
        },
      },
      {
        name: "Ail",
        length: 585,
        beds: {
          first: [{ name: "Ail", length: 16 }],
          last: [{ name: "Engrais vert", length: 16 }],
        },
      },
      {
        name: "Verdures-racines",
        length: 585,
        beds: {
          first: [
            { name: "Mesclun", length: 4 },
            { name: "Haricot", length: 4 },
            { name: "Carotte", length: 4 },
            { name: "Laitue", length: 4 },
          ],
          last: [{ name: "Ail", length: 16 }],
        },
      },
      {
        name: "Solanacées",
        length: 655,
        beds: {
          first: [{ name: "Engrais vert", length: 16 }],
          last: [
            { name: "Aubergine", length: 5 },
            { name: "Cerise de terre", length: 2 },
            { name: "Piment fort", length: 1 },
            { name: "Poivron", length: 2 },
            { name: "Melon", length: 6 },
          ],
        },
      },
      {
        name: "Verdures-racines",
        length: 655,
        beds: {
          first: [
            { name: "Haricot", length: 2 },
            { name: "Radis", length: 1 },
            { name: "Navet", length: 1 },
            { name: "Carotte", length: 2 },
            { name: "Roquette", length: 2 },
            { name: "Laitue", length: 2 },
            { name: "Betterave", length: 2 },
            { name: "Haricot", length: 4 },
          ],
          last: [
            { name: "Épinard", length: 2 },
            { name: "Laitue", length: 2 },
            { name: "Roquette", length: 1 },
            { name: "Moutarde", length: 1 },
            { name: "Bette", length: 2 },
            { name: "Haricot", length: 2 },
            { name: "Roquette", length: 2 },
            { name: "Épinard", length: 4 },
          ],
        },
      },
      {
        name: "Cuccurbites et crucifères primeurs",
        length: 655,
        beds: {
          first: [{ name: "Engrais vert", length: 16 }],
          last: [
            { name: "Brocoli", length: 4 },
            { name: "Chou d'été", length: 2 },
            { name: "Chou de Bruxelles", length: 1 },
            { name: "Courgette", length: 1 },
            { name: "Chou-fleur", length: 2 },
            { name: "Brocoli", length: 4 },
            { name: "Chou-rave", length: 2 },
          ],
        },
      },
      {
        name: "Verdures-racines",
        length: 655,
        beds: {
          first: [
            { name: "Carotte", length: 4 },
            { name: "Coriandre", length: 1 },
            { name: "Navet", length: 1 },
            { name: "Radis", length: 1 },
            { name: "Roquette", length: 1 },
            { name: "Betterave", length: 2 },
            { name: "Chicorée", length: 1 },
            { name: "Pois", length: 4 },
            { name: "Laitue", length: 1 },
          ],
          last: [
            { name: "Laitue", length: 4 },
            { name: "Mesclun", length: 9 },
            { name: "Chou chinois", length: 1 },
            { name: "Chou collard", length: 1 },
            { name: "Fenouil", length: 1 },
          ],
        },
      },
      {
        name: "Liliacées",
        length: 750,
        beds: {
          first: [
            { name: "Oignon vert", length: 6 },
            { name: "Poireau", length: 4 },
            { name: "Oignon de conservation", length: 6 },
          ],
          last: [{ name: "Engrais vert", length: 16 }],
        },
      },
      {
        name: "Verdures-racines",
        length: 750,
        beds: {
          first: [{ name: "Mesclun", length: 16 }],
          last: [
            { name: "Carotte", length: 2 },
            { name: "Haricot", length: 2 },
            { name: "Radis d'hiver", length: 3 },
            { name: "Chicorée", length: 1 },
            { name: "Kale", length: 2 },
            { name: "Chou chinois", length: 2 },
            { name: "Persil", length: 1 },
            { name: "Navet", length: 1 },
            { name: "Radis", length: 1 },
            { name: "Navet", length: 1 },
          ],
        },
      },
      {
        name: "Solanacées",
        length: 750,
        beds: {
          first: [{ name: "Moutarde", length: 16 }],
          last: [{ name: "Tomate", length: 16 }],
        },
      },
      {
        name: "Verdures-racines",
        length: 750,
        beds: {
          first: [
            { name: "Carotte", length: 4 },
            { name: "Coriandre", length: 1 },
            { name: "Navet", length: 1 },
            { name: "Radis", length: 1 },
            { name: "Roquette", length: 1 },
            { name: "Betterave", length: 2 },
            { name: "Chicorée", length: 1 },
            { name: "Pois", length: 4 },
            { name: "Laitue", length: 1 },
          ],
          last: [
            { name: "Laitue", length: 4 },
            { name: "Mesclun", length: 9 },
            { name: "Chou chinois", length: 1 },
            { name: "Chou collard", length: 1 },
            { name: "Fenouil", length: 1 },
          ],
        },
      },
    ],
    plants: {
      Ail: {
        Length: 12,
        Width: 15,
        StaggeredWidth: 14,
        Depth: 5,
        AutonomyFor10: 96,
      },
      Amarante: {
        Length: 45,
        Width: 60,
        StaggeredWidth: 56,
        Depth: 0,
        AutonomyFor10: 24,
      },
      Aneth: {
        Length: 5,
        Width: 60,
        StaggeredWidth: 60,
        Depth: 0.5,
        AutonomyFor10: 48,
      },
      Arroche: {
        Length: 5,
        Width: 30,
        StaggeredWidth: 30,
        Depth: 1,
        AutonomyFor10: 0,
      },
      Asperge: {
        Length: 45,
        Width: 120,
        StaggeredWidth: 118,
        Depth: 1,
        AutonomyFor10: 48,
      },
      Aubergine: {
        Length: 45,
        Width: 60,
        StaggeredWidth: 56,
        Depth: 0.5,
        AutonomyFor10: 0,
      },
      "Avoine et pois": {
        Length: 2,
        Width: 2,
        StaggeredWidth: 2,
        Depth: 0,
        AutonomyFor10: 0,
      },
      Basilic: {
        Length: 30,
        Width: 50,
        StaggeredWidth: 48,
        Depth: 0,
        AutonomyFor10: 200,
      },
      "Bette à carde": {
        Length: 15,
        Width: 45,
        StaggeredWidth: 45,
        Depth: 1,
        AutonomyFor10: 0,
      },
      Betterave: {
        Length: 4,
        Width: 15,
        StaggeredWidth: 15,
        Depth: 1,
        AutonomyFor10: 300,
      },
      "Bok choy": {
        Length: 25,
        Width: 30,
        StaggeredWidth: 28,
        Depth: 1,
        AutonomyFor10: 800,
      },
      Bourrache: {
        Length: 30,
        Width: 45,
        StaggeredWidth: 43,
        Depth: 1,
        AutonomyFor10: 48,
      },
      Brocoli: {
        Length: 45,
        Width: 60,
        StaggeredWidth: 56,
        Depth: 0.5,
        AutonomyFor10: 20,
      },
      Camomille: {
        Length: 30,
        Width: 60,
        StaggeredWidth: 59,
        Depth: 0,
        AutonomyFor10: 36,
      },
      Cantaloup: {
        Length: 50,
        Width: 75,
        StaggeredWidth: 71,
        Depth: 1.5,
        AutonomyFor10: 0,
      },
      Capucine: {
        Length: 30,
        Width: 30,
        StaggeredWidth: 26,
        Depth: 1.5,
        AutonomyFor10: 48,
      },
      Caraganier: {
        Length: 200,
        Width: 300,
        StaggeredWidth: 283,
        Depth: 1.5,
        AutonomyFor10: 12,
      },
      Carotte: {
        Length: 2,
        Width: 15,
        StaggeredWidth: 15,
        Depth: 0.5,
        AutonomyFor10: 2000,
      },
      Cataire: {
        Length: 40,
        Width: 40,
        StaggeredWidth: 35,
        Depth: 0.5,
        AutonomyFor10: 4,
      },
      Céleri: {
        Length: 20,
        Width: 40,
        StaggeredWidth: 39,
        Depth: 0,
        AutonomyFor10: 24,
      },
      "Céleri-rave": {
        Length: 20,
        Width: 60,
        StaggeredWidth: 60,
        Depth: 0,
        AutonomyFor10: 0,
      },
      "Cerise de terre": {
        Length: 50,
        Width: 75,
        StaggeredWidth: 71,
        Depth: 0,
        AutonomyFor10: 0,
      },
      Chervis: {
        Length: "",
        Width: "",
        StaggeredWidth: 0,
        Depth: "",
        AutonomyFor10: 24,
      },
      Chicorée: {
        Length: 20,
        Width: 30,
        StaggeredWidth: 29,
        Depth: 0,
        AutonomyFor10: 80,
      },
      Chou: {
        Length: 30,
        Width: 45,
        StaggeredWidth: 43,
        Depth: 1,
        AutonomyFor10: 80,
      },
      "Chou de Bruxelles": {
        Length: 30,
        Width: 45,
        StaggeredWidth: 43,
        Depth: 0.5,
        AutonomyFor10: 0,
      },
      "Chou marin": {
        Length: 120,
        Width: 120,
        StaggeredWidth: 104,
        Depth: 2,
        AutonomyFor10: 24,
      },
      "Chou-fleur": {
        Length: 30,
        Width: 60,
        StaggeredWidth: 59,
        Depth: 0.5,
        AutonomyFor10: 20,
      },
      "Chou-rave": {
        Length: 15,
        Width: 30,
        StaggeredWidth: 30,
        Depth: 0.5,
        AutonomyFor10: 80,
      },
      Ciboulette: {
        Length: 20,
        Width: 30,
        StaggeredWidth: 29,
        Depth: 1,
        AutonomyFor10: 120,
      },
      Citrouille: {
        Length: 75,
        Width: 75,
        StaggeredWidth: 65,
        Depth: 2,
        AutonomyFor10: 12,
      },
      Concombre: {
        Length: 45,
        Width: 75,
        StaggeredWidth: 72,
        Depth: 1,
        AutonomyFor10: 18,
      },
      Consoude: {
        Length: "",
        Width: "",
        StaggeredWidth: 0,
        Depth: "",
        AutonomyFor10: 6,
      },
      Coriandre: {
        Length: 15,
        Width: 30,
        StaggeredWidth: 30,
        Depth: 0.5,
        AutonomyFor10: 0,
      },
      "Courge musqué": {
        Length: 75,
        Width: 75,
        StaggeredWidth: 65,
        Depth: 2,
        AutonomyFor10: 24,
      },
      Courgette: {
        Length: 60,
        Width: 120,
        StaggeredWidth: 117,
        Depth: 2,
        AutonomyFor10: 12,
      },
      Cresson: {
        Length: 1,
        Width: 10,
        StaggeredWidth: 10,
        Depth: 0.5,
        AutonomyFor10: 200,
      },
      "Échalote de Sainte-Anne": {
        Length: 30,
        Width: 30,
        StaggeredWidth: 26,
        Depth: 0,
        AutonomyFor10: 0,
      },
      Échinacée: {
        Length: 30,
        Width: 60,
        StaggeredWidth: 59,
        Depth: 0,
        AutonomyFor10: 24,
      },
      Épinard: {
        Length: 5,
        Width: 30,
        StaggeredWidth: 30,
        Depth: 1.5,
        AutonomyFor10: 0,
      },
      Fraise: {
        Length: 30,
        Width: 25,
        StaggeredWidth: 20,
        Depth: "",
        AutonomyFor10: 0,
      },
      Gombo: {
        Length: 20,
        Width: 60,
        StaggeredWidth: 60,
        Depth: 1.5,
        AutonomyFor10: 0,
      },
      "Haricot grimpant": {
        Length: 12,
        Width: 45,
        StaggeredWidth: 45,
        Depth: 2,
        AutonomyFor10: 100,
      },
      "Haricot nain": {
        Length: 12,
        Width: 45,
        StaggeredWidth: 45,
        Depth: 2,
        AutonomyFor10: 200,
      },
      "Haricot sec": {
        Length: 12,
        Width: 45,
        StaggeredWidth: 45,
        Depth: 2,
        AutonomyFor10: 800,
      },
      Kale: {
        Length: 45,
        Width: 60,
        StaggeredWidth: 56,
        Depth: 1,
        AutonomyFor10: 72,
      },
      Kiwi: {
        Length: 150,
        Width: 180,
        StaggeredWidth: 164,
        Depth: "",
        AutonomyFor10: 0,
      },
      Laitue: {
        Length: 20,
        Width: 40,
        StaggeredWidth: 39,
        Depth: 0,
        AutonomyFor10: 600,
      },
      Lavande: {
        Length: 60,
        Width: 60,
        StaggeredWidth: 52,
        Depth: 0.5,
        AutonomyFor10: 24,
      },
      Maïs: {
        Length: 15,
        Width: 30,
        StaggeredWidth: 30,
        Depth: 2,
        AutonomyFor10: 0,
      },
      "Maïs à farine": {
        Length: 15,
        Width: 30,
        StaggeredWidth: 30,
        Depth: 2,
        AutonomyFor10: 120,
      },
      Marjolaine: {
        Length: 30,
        Width: 30,
        StaggeredWidth: 26,
        Depth: 0,
        AutonomyFor10: 0,
      },
      Melon: {
        Length: 35,
        Width: 75,
        StaggeredWidth: 73,
        Depth: 1.5,
        AutonomyFor10: 0,
      },
      "Melon miel": {
        Length: 75,
        Width: 75,
        StaggeredWidth: 65,
        Depth: 1.5,
        AutonomyFor10: 0,
      },
      Menthe: {
        Length: 60,
        Width: 60,
        StaggeredWidth: 52,
        Depth: 0.5,
        AutonomyFor10: 6,
      },
      Millepertuis: {
        Length: 45,
        Width: 80,
        StaggeredWidth: 77,
        Depth: 0,
        AutonomyFor10: 12,
      },
      Molène: {
        Length: 45,
        Width: 90,
        StaggeredWidth: 88,
        Depth: 0,
        AutonomyFor10: 12,
      },
      Monarde: {
        Length: "",
        Width: "",
        StaggeredWidth: 0,
        Depth: "",
        AutonomyFor10: 18,
      },
      Moutarde: {
        Length: 1,
        Width: 30,
        StaggeredWidth: 30,
        Depth: 0.5,
        AutonomyFor10: 400,
      },
      Navet: {
        Length: 5,
        Width: 20,
        StaggeredWidth: 20,
        Depth: 0.5,
        AutonomyFor10: 400,
      },
      Oignon: {
        Length: 20,
        Width: 25,
        StaggeredWidth: 23,
        Depth: 1,
        AutonomyFor10: 66,
      },
      "Oignon vert": {
        Length: 10,
        Width: 25,
        StaggeredWidth: 25,
        Depth: 1,
        AutonomyFor10: 0,
      },
      Origan: {
        Length: 30,
        Width: 45,
        StaggeredWidth: 43,
        Depth: 0,
        AutonomyFor10: 8,
      },
      Ortie: {
        Length: "",
        Width: "",
        StaggeredWidth: 0,
        Depth: "",
        AutonomyFor10: 12,
      },
      Oseille: {
        Length: 30,
        Width: 30,
        StaggeredWidth: 26,
        Depth: 0,
        AutonomyFor10: 12,
      },
      Panais: {
        Length: 10,
        Width: 20,
        StaggeredWidth: 20,
        Depth: 1.5,
        AutonomyFor10: 300,
      },
      Persil: {
        Length: 20,
        Width: 45,
        StaggeredWidth: 44,
        Depth: 0.5,
        AutonomyFor10: 36,
      },
      Piment: {
        Length: 40,
        Width: 50,
        StaggeredWidth: 46,
        Depth: 0.5,
        AutonomyFor10: 8,
      },
      Plantain: {
        Length: 30,
        Width: 45,
        StaggeredWidth: 43,
        Depth: 0.5,
        AutonomyFor10: 8,
      },
      Poireau: {
        Length: 7.5,
        Width: 30,
        StaggeredWidth: 30,
        Depth: 1,
        AutonomyFor10: 120,
      },
      "Pois des neiges": {
        Length: 2,
        Width: 45,
        StaggeredWidth: 45,
        Depth: 2,
        AutonomyFor10: 400,
      },
      "Pois mange-tout": {
        Length: 2,
        Width: 45,
        StaggeredWidth: 45,
        Depth: 2,
        AutonomyFor10: 400,
      },
      Poivron: {
        Length: 30,
        Width: 50,
        StaggeredWidth: 48,
        Depth: 0.5,
        AutonomyFor10: 48,
      },
      "Pomme de terre": {
        Length: "",
        Width: "",
        StaggeredWidth: 0,
        Depth: "",
        AutonomyFor10: 120,
      },
      Radis: {
        Length: 2,
        Width: 20,
        StaggeredWidth: 20,
        Depth: 1.5,
        AutonomyFor10: 100,
      },
      "Radis d'hiver": {
        Length: 2,
        Width: 20,
        StaggeredWidth: 20,
        Depth: 1.5,
        AutonomyFor10: 300,
      },
      Raifort: {
        Length: "",
        Width: "",
        StaggeredWidth: 0,
        Depth: "",
        AutonomyFor10: 2,
      },
      Rhubarbe: {
        Length: 100,
        Width: 140,
        StaggeredWidth: 131,
        Depth: 1.5,
        AutonomyFor10: 0,
      },
      Roquette: {
        Length: 5,
        Width: 30,
        StaggeredWidth: 30,
        Depth: 0.5,
        AutonomyFor10: 0,
      },
      Rutabaga: {
        Length: 3,
        Width: 20,
        StaggeredWidth: 20,
        Depth: 1,
        AutonomyFor10: 400,
      },
      Sarriette: {
        Length: 20,
        Width: 30,
        StaggeredWidth: 29,
        Depth: 0,
        AutonomyFor10: 0,
      },
      Sauge: {
        Length: 30,
        Width: 45,
        StaggeredWidth: 43,
        Depth: 0.5,
        AutonomyFor10: 4,
      },
      Scorsonère: {
        Length: 20,
        Width: 20,
        StaggeredWidth: 18,
        Depth: 1,
        AutonomyFor10: 12,
      },
      "Soja edamame": {
        Length: 30,
        Width: 60,
        StaggeredWidth: 59,
        Depth: 2,
        AutonomyFor10: 0,
      },
      Souchet: {
        Length: 45,
        Width: 90,
        StaggeredWidth: 88,
        Depth: 2,
        AutonomyFor10: 53,
      },
      Souci: {
        Length: 30,
        Width: 45,
        StaggeredWidth: 43,
        Depth: 0.5,
        AutonomyFor10: 24,
      },
      Thym: {
        Length: 30,
        Width: 30,
        StaggeredWidth: 26,
        Depth: 0,
        AutonomyFor10: 12,
      },
      Tomate: {
        Length: 30,
        Width: 40,
        StaggeredWidth: 38,
        Depth: 0.5,
        AutonomyFor10: 72,
      },
      "Tomate cerise": {
        Length: 30,
        Width: 40,
        StaggeredWidth: 38,
        Depth: 0.5,
        AutonomyFor10: 0,
      },
      "Tomate italienne": {
        Length: 30,
        Width: 40,
        StaggeredWidth: 38,
        Depth: 0.5,
        AutonomyFor10: 0,
      },
      Topinambour: {
        Length: 60,
        Width: 75,
        StaggeredWidth: 69,
        Depth: 10,
        AutonomyFor10: 48,
      },
      Tournesol: {
        Length: 40,
        Width: 60,
        StaggeredWidth: 57,
        Depth: 2,
        AutonomyFor10: 48,
      },
    },
  },
  reducers: {
    convertCelsiusToFahrenheit: (state, { payload }) => {
      state.celsius = payload;
      if (isNaN(state.celsius)) {
        state.fahrenheit = "Non Numérique";
      } else {
        state.fahrenheit = (Number(state.celsius) * 9) / 5 + 32;
      }
    },
  },
});

export const { convertCelsiusToFahrenheit } = rotateSlice.actions;

export default rotateSlice.reducer;
