backend:
  name: github
  repo: audetpascale/audetpascale
  branch: main

site_url: https://j-art-diner.audetpascale.com

media_folder: j-art-diner/static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "j-art-diner/src/pages/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Item order", name: "itemOrder", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
