import { createSlice } from "@reduxjs/toolkit";

export const dataSlice = createSlice({
  name: "data",
  initialState: {
    autonomy: 10,
    plants: [
      {
        name: "Ail",
        length: 12,
        width: 15,
        staggeredWidth: 14,
        depth: 5,
        autonomyFor10: 72,
        autonomy: 72,
        link: "https://www.ecoumene.com/produit/semences/bulbes-cormes-turbercules/ail-cultive/ail-music/",
      },
      {
        name: "Amarante",
        length: 45,
        width: 60,
        staggeredWidth: 56,
        depth: 0,
        autonomyFor10: 24,
        autonomy: 24,
        link: "https://www.ecoumene.com/produit/semences/herbacees/amarante-hopi-red-dye-bio/",
      },
      {
        name: "Aneth",
        length: 5,
        width: 60,
        staggeredWidth: 60,
        depth: 0.5,
        autonomyFor10: 48,
        autonomy: 48,
        link: "https://www.ecoumene.com/produit/semences/herbacees/aneth-de-jardin-bio/",
      },
      {
        name: "Arroche",
        length: 5,
        width: 30,
        staggeredWidth: 30,
        depth: 1,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/arroche-aurora-mix-bio/",
      },
      {
        name: "Asperge",
        length: 45,
        width: 120,
        staggeredWidth: 118,
        depth: 1,
        autonomyFor10: 48,
        autonomy: 48,
        link: "https://www.terrepromise.ca/produit/asperge/",
      },
      {
        name: "Avoine et pois",
        length: 2,
        width: 2,
        staggeredWidth: 2,
        depth: 0,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/produits-horticoles/sol-vivant/engrais/avoine-et-pois/",
      },
      {
        name: "Basilic",
        length: 30,
        width: 50,
        staggeredWidth: 48,
        depth: 0,
        autonomyFor10: 200,
        autonomy: 200,
        link: "https://www.ecoumene.com/produit/semences/herbacees/basilic-en-melange/",
      },
      {
        name: "Bette à carde",
        length: 15,
        width: 45,
        staggeredWidth: 45,
        depth: 1,
        autonomyFor10: 24,
        autonomy: 24,
        link: "https://www.ecoumene.com/produit/semences/potageres/bette-a-carde-rainbow-mix-bio/",
      },
      {
        name: "Betterave",
        length: 4,
        width: 15,
        staggeredWidth: 15,
        depth: 1,
        autonomyFor10: 300,
        autonomy: 300,
        link: "https://www.ecoumene.com/produit/semences/potageres/betterave-early-wonder-tall-top-bio/",
      },
      {
        name: "Bok choy",
        length: 25,
        width: 30,
        staggeredWidth: 28,
        depth: 1,
        autonomyFor10: 800,
        autonomy: 800,
        link: "https://www.ecoumene.com/produit/semences/potageres/chou/chinois/chou-chinois-pak-choi-shanghai-bio/",
      },
      {
        name: "Bourrache",
        length: 30,
        width: 45,
        staggeredWidth: 43,
        depth: 1,
        autonomyFor10: 48,
        autonomy: 48,
        link: "https://www.ecoumene.com/produit/semences/herbacees/bourrache-officinale-bio/",
      },
      {
        name: "Brocoli",
        length: 45,
        width: 60,
        staggeredWidth: 56,
        depth: 0.5,
        autonomyFor10: 20,
        autonomy: 20,
        link: "https://www.ecoumene.com/produit/semences/potageres/brocoli-de-cicco-bio/",
      },
      {
        name: "Camomille",
        length: 30,
        width: 60,
        staggeredWidth: 59,
        depth: 0,
        autonomyFor10: 36,
        autonomy: 36,
        link: "https://www.ecoumene.com/produit/semences/herbacees/camomille-grande-bio/",
      },
      {
        name: "Cantaloup",
        length: 35,
        width: 75,
        staggeredWidth: 73,
        depth: 1.5,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/melon/melon-cantaloup/melon-banana-bio/",
      },
      {
        name: "Capucine",
        length: 30,
        width: 30,
        staggeredWidth: 26,
        depth: 1.5,
        autonomyFor10: 48,
        autonomy: 48,
        link: "https://www.ecoumene.com/produit/semences/herbacees/capucine-jewel-bio/",
      },
      {
        name: "Caraganier",
        length: 200,
        width: 300,
        staggeredWidth: 283,
        depth: 1.5,
        autonomyFor10: 12,
        autonomy: 12,
        link: "https://www.ecoumene.com/produit/semences/arbres-et-arbustes/caraganier-de-siberie-bio/",
      },
      {
        name: "Carotte",
        length: 2,
        width: 15,
        staggeredWidth: 15,
        depth: 0.5,
        autonomyFor10: 2000,
        autonomy: 2000,
        link: "https://www.ecoumene.com/produit/semences/potageres/carotte-red-cored-chantenay-bio/",
      },
      {
        name: "Cataire",
        length: 40,
        width: 40,
        staggeredWidth: 35,
        depth: 0.5,
        autonomyFor10: 4,
        autonomy: 4,
        link: "https://www.ecoumene.com/produit/semences/herbacees/cataire-herbe-aux-chats-bio/",
      },
      {
        name: "Céleri",
        length: 20,
        width: 40,
        staggeredWidth: 39,
        depth: 0,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/celeri-plein-blanc-dore-bio/",
      },
      {
        name: "Cerise de terre",
        length: 50,
        width: 75,
        staggeredWidth: 71,
        depth: 0,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/cerise-de-terre-geante-bio/",
      },
      {
        name: "Chervis",
        length: "",
        width: "",
        staggeredWidth: 0,
        depth: "",
        autonomyFor10: 24,
        autonomy: 24,
        link: "https://www.terrepromise.ca/produit/chervis/",
      },
      {
        name: "Chicorée",
        length: 20,
        width: 30,
        staggeredWidth: 29,
        depth: 0,
        autonomyFor10: 80,
        autonomy: 80,
        link: "https://www.ecoumene.com/produit/semences/potageres/chicoree-sauvage-catalogna-bio/",
      },
      {
        name: "Chou",
        length: 30,
        width: 45,
        staggeredWidth: 43,
        depth: 1,
        autonomyFor10: 80,
        autonomy: 80,
        link: "https://www.ecoumene.com/produit/semences/potageres/chou/pomme/chou-milan-de-pontoise-bio/",
      },
      {
        name: "Chou marin",
        length: 120,
        width: 120,
        staggeredWidth: 104,
        depth: 2,
        autonomyFor10: 24,
        autonomy: 24,
        link: "https://www.ecoumene.com/produit/semences/potageres/chou/chou-marin/chou-marin-lily-white-bio/",
      },
      {
        name: "Chou-fleur",
        length: 30,
        width: 60,
        staggeredWidth: 59,
        depth: 0.5,
        autonomyFor10: 20,
        autonomy: 20,
        link: "https://semencesduportage.com/catalogue/plante-legumiere/chou-fleur/",
      },
      {
        name: "Chou-rave",
        length: 15,
        width: 30,
        staggeredWidth: 30,
        depth: 0.5,
        autonomyFor10: 80,
        autonomy: 80,
        link: "https://www.ecoumene.com/produit/semences/potageres/chou/chou-rave/chou-rave-en-melange/",
      },
      {
        name: "Ciboulette",
        length: 20,
        width: 30,
        staggeredWidth: 29,
        depth: 1,
        autonomyFor10: 120,
        autonomy: 120,
        link: "https://www.ecoumene.com/produit/semences/herbacees/ciboulette-de-jardin-bio/",
      },
      {
        name: "Citrouille",
        length: 75,
        width: 75,
        staggeredWidth: 65,
        depth: 2,
        autonomyFor10: 12,
        autonomy: 12,
        link: "https://www.ecoumene.com/produit/semences/potageres/citrouille-cheyenne-bush-bio/",
      },
      {
        name: "Concombre",
        length: 45,
        width: 75,
        staggeredWidth: 72,
        depth: 1,
        autonomyFor10: 18,
        autonomy: 18,
        link: "https://www.ecoumene.com/produit/semences/potageres/concombre/concombre-americain/concombre-tante-alice-bio/",
      },
      {
        name: "Consoude",
        length: "",
        width: "",
        staggeredWidth: 0,
        depth: "",
        autonomyFor10: 6,
        autonomy: 6,
        link: "https://www.terrepromise.ca/produit/consoude/",
      },
      {
        name: "Coriandre",
        length: 15,
        width: 30,
        staggeredWidth: 30,
        depth: 0.5,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/herbacees/coriandre-santo-bio/",
      },
      {
        name: "Courge musqué",
        length: 75,
        width: 75,
        staggeredWidth: 65,
        depth: 2,
        autonomyFor10: 24,
        autonomy: 24,
        link: "https://www.ecoumene.com/produit/semences/potageres/courge-ponca-baby-butternut-bio/",
      },
      {
        name: "Courgette",
        length: 60,
        width: 120,
        staggeredWidth: 117,
        depth: 2,
        autonomyFor10: 12,
        autonomy: 12,
        link: "https://www.ecoumene.com/produit/semences/potageres/courgette-ronde-de-nice-bio/",
      },
      {
        name: "Cresson",
        length: 1,
        width: 10,
        staggeredWidth: 10,
        depth: 0.5,
        autonomyFor10: 200,
        autonomy: 200,
        link: "https://www.ecoumene.com/produit/semences/herbacees/cresson-alenois-frise-bio/",
      },
      {
        name: "Échalote de Sainte-Anne",
        length: 30,
        width: 30,
        staggeredWidth: 26,
        depth: 0,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/echalote-de-sainte-anne/",
      },
      {
        name: "Échinacée",
        length: 30,
        width: 60,
        staggeredWidth: 59,
        depth: 0,
        autonomyFor10: 24,
        autonomy: 24,
        link: "https://www.ecoumene.com/produit/semences/herbacees/echinacee-pourpre-bio/",
      },
      {
        name: "Épinard",
        length: 5,
        width: 30,
        staggeredWidth: 30,
        depth: 1.5,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/epinard-bloomsdale-bio/",
      },
      {
        name: "Fraise",
        length: 30,
        width: 25,
        staggeredWidth: 20,
        depth: "",
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/herbacees/fraisier-alpin-yellow-wonder/",
      },
      {
        name: "Haricot grimpant",
        length: 12,
        width: 45,
        staggeredWidth: 45,
        depth: 2,
        autonomyFor10: 100,
        autonomy: 100,
        link: "https://www.ecoumene.com/produit/semences/potageres/haricot/grimpant/haricot-grand-maman-dinel-bio/",
      },
      {
        name: "Haricot nain",
        length: 12,
        width: 45,
        staggeredWidth: 45,
        depth: 2,
        autonomyFor10: 200,
        autonomy: 200,
        link: "https://www.ecoumene.com/produit/semences/potageres/haricot/nain/haricot-fortin-bio/",
      },
      {
        name: "Haricot sec",
        length: 12,
        width: 45,
        staggeredWidth: 45,
        depth: 2,
        autonomyFor10: 800,
        autonomy: 800,
        link: "https://www.ecoumene.com/produit/semences/potageres/haricot/nain/haricot-hopi-black-bio/",
      },
      {
        name: "Kale",
        length: 45,
        width: 60,
        staggeredWidth: 56,
        depth: 1,
        autonomyFor10: 72,
        autonomy: 72,
        link: "https://www.ecoumene.com/produit/semences/potageres/chou/frise-kale/chou-frise-dwarf-blue-scotch-bio/",
      },
      {
        name: "Laitue",
        length: 20,
        width: 40,
        staggeredWidth: 39,
        depth: 0,
        autonomyFor10: 600,
        autonomy: 600,
        link: "https://www.ecoumene.com/produit/semences/potageres/laitue/laitue-pommee/laitue-pommee-grosse-blonde-paresseuse-bio/",
      },
      {
        name: "Lavande",
        length: 60,
        width: 60,
        staggeredWidth: 52,
        depth: 0.5,
        autonomyFor10: 24,
        autonomy: 24,
        link: "https://www.ecoumene.com/produit/semences/herbacees/lavande-officinale-bio/",
      },
      {
        name: "Maïs",
        length: 15,
        width: 30,
        staggeredWidth: 30,
        depth: 2,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/mais/mais-sucre/mais-golden-bantam-bio/",
      },
      {
        name: "Maïs à farine",
        length: 15,
        width: 30,
        staggeredWidth: 30,
        depth: 2,
        autonomyFor10: 120,
        autonomy: 120,
        link: "https://www.ecoumene.com/produit/semences/potageres/mais/mais-a-moudre/mais-abenaki-bio/",
      },
      {
        name: "Marjolaine",
        length: 30,
        width: 30,
        staggeredWidth: 26,
        depth: 0,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/herbacees/marjolaine-des-jardins-bio/",
      },
      {
        name: "Melon",
        length: 35,
        width: 75,
        staggeredWidth: 73,
        depth: 1.5,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/melon/melon-deau/melon-sweet-siberian-bio/",
      },
      {
        name: "Menthe",
        length: 60,
        width: 60,
        staggeredWidth: 52,
        depth: 0.5,
        autonomyFor10: 6,
        autonomy: 6,
        link: "https://www.whperron.com/fr/9188-menthe-verte.html",
      },
      {
        name: "Millepertuis",
        length: 45,
        width: 80,
        staggeredWidth: 77,
        depth: 0,
        autonomyFor10: 12,
        autonomy: 12,
        link: "https://www.ecoumene.com/produit/semences/herbacees/millepertuis-helos-bio/",
      },
      {
        name: "Molène",
        length: 45,
        width: 90,
        staggeredWidth: 88,
        depth: 0,
        autonomyFor10: 12,
        autonomy: 12,
        link: "https://www.ecoumene.com/produit/semences/herbacees/molene-dolympe-bio/",
      },
      {
        name: "Monarde",
        length: "",
        width: "",
        staggeredWidth: 0,
        depth: "",
        autonomyFor10: 18,
        autonomy: 18,
        link: "https://www.ecoumene.com/produit/semences/herbacees/monarde-panorama-en-melange-bio/",
      },
      {
        name: "Moutarde",
        length: 1,
        width: 30,
        staggeredWidth: 30,
        depth: 0.5,
        autonomyFor10: 400,
        autonomy: 400,
        link: "https://www.ecoumene.com/produit/semences/herbacees/moutarde-great-wave-miike-bio/",
      },
      {
        name: "Navet",
        length: 5,
        width: 20,
        staggeredWidth: 20,
        depth: 0.5,
        autonomyFor10: 400,
        autonomy: 400,
        link: "https://www.ecoumene.com/produit/semences/potageres/navet-blanc-a-collet-violet-bio/",
      },
      {
        name: "Oignon",
        length: 20,
        width: 25,
        staggeredWidth: 23,
        depth: 1,
        autonomyFor10: 600,
        autonomy: 600,
        link: "https://www.ecoumene.com/produit/semences/potageres/oignon-patate-3-bulbes/",
      },
      {
        name: "Oignon vert",
        length: 10,
        width: 25,
        staggeredWidth: 25,
        depth: 1,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/oignon/oignon-a-botteler/oignon-a-botteler-parade-bio/",
      },
      {
        name: "Origan",
        length: 30,
        width: 45,
        staggeredWidth: 43,
        depth: 0,
        autonomyFor10: 8,
        autonomy: 8,
        link: "https://www.ecoumene.com/produit/semences/herbacees/origan-commun-bio/",
      },
      {
        name: "Ortie",
        length: "",
        width: "",
        staggeredWidth: 0,
        depth: "",
        autonomyFor10: 12,
        autonomy: 12,
        link: "https://www.ecoumene.com/produit/produits-de-la-foret/plantes-foret/simples/feuilles/urtica-dioica/",
      },
      {
        name: "Oseille",
        length: 30,
        width: 30,
        staggeredWidth: 26,
        depth: 0,
        autonomyFor10: 12,
        autonomy: 12,
        link: "https://www.ecoumene.com/produit/semences/potageres/oseille-de-jardin-bio/",
      },
      {
        name: "Panais",
        length: 10,
        width: 20,
        staggeredWidth: 20,
        depth: 1.5,
        autonomyFor10: 300,
        autonomy: 300,
        link: "https://www.ecoumene.com/produit/semences/potageres/panais-halblange-bio/",
      },
      {
        name: "Persil",
        length: 20,
        width: 45,
        staggeredWidth: 44,
        depth: 0.5,
        autonomyFor10: 36,
        autonomy: 36,
        link: "https://www.ecoumene.com/produit/semences/herbacees/persil-italien-bio/",
      },
      {
        name: "Piment",
        length: 40,
        width: 50,
        staggeredWidth: 46,
        depth: 0.5,
        autonomyFor10: 8,
        autonomy: 8,
        link: "https://www.ecoumene.com/produit/semences/potageres/piment/chaud/piment-gorria-bio/",
      },
      {
        name: "Plantain",
        length: 30,
        width: 45,
        staggeredWidth: 43,
        depth: 0.5,
        autonomyFor10: 8,
        autonomy: 8,
        link: "https://www.ecoumene.com/produit/semences/herbacees/plantain-lanceole-bio/",
      },
      {
        name: "Poireau",
        length: 7.5,
        width: 30,
        staggeredWidth: 30,
        depth: 1,
        autonomyFor10: 120,
        autonomy: 120,
        link: "https://www.ecoumene.com/produit/semences/potageres/poireau-bleu-de-solaise-bio/",
      },
      {
        name: "Pois des neiges",
        length: 2,
        width: 45,
        staggeredWidth: 45,
        depth: 2,
        autonomyFor10: 400,
        autonomy: 400,
        link: "https://www.ecoumene.com/produit/semences/potageres/pois/pois-des-neiges/pois-golden-sweet-bio/",
      },
      {
        name: "Pois mange-tout",
        length: 2,
        width: 45,
        staggeredWidth: 45,
        depth: 2,
        autonomyFor10: 400,
        autonomy: 400,
        link: "https://www.ecoumene.com/produit/semences/potageres/pois/pois-mange-tout/pois-cascadia-bio/",
      },
      {
        name: "Poivron",
        length: 30,
        width: 50,
        staggeredWidth: 48,
        depth: 0.5,
        autonomyFor10: 48,
        autonomy: 48,
        link: "https://www.ecoumene.com/produit/semences/potageres/poivron/type-mini/poivron-doe-hill-bio/",
      },
      {
        name: "Pomme de terre",
        length: "",
        width: "",
        staggeredWidth: 0,
        depth: "",
        autonomyFor10: 120,
        autonomy: 120,
        link: "https://www.ecoumene.com/produit/semences/herbacees/apios-americana/",
      },
      {
        name: "Radis",
        length: 2,
        width: 20,
        staggeredWidth: 20,
        depth: 1.5,
        autonomyFor10: 400,
        autonomy: 400,
        link: "https://www.ecoumene.com/produit/semences/potageres/radis/radis-de-printemps/radis-petit-dejeuner-francais-bio/",
      },
      {
        name: "Radis d'hiver",
        length: 2,
        width: 20,
        staggeredWidth: 20,
        depth: 1.5,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/radis/radis-dhiver/radis-melon-deau-bio/",
      },
      {
        name: "Raifort",
        length: "",
        width: "",
        staggeredWidth: 0,
        depth: "",
        autonomyFor10: 2,
        autonomy: 2,
        link: "https://www.terrepromise.ca/produit/raifort-vivace/",
      },
      {
        name: "Rhubarbe",
        length: 100,
        width: 140,
        staggeredWidth: 131,
        depth: 1.5,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/rhubarbe-victoria-bio/",
      },
      {
        name: "Roquette",
        length: 5,
        width: 30,
        staggeredWidth: 30,
        depth: 0.5,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/roquette-italienne-sylvetta-bio/",
      },
      {
        name: "Rutabaga",
        length: 3,
        width: 20,
        staggeredWidth: 20,
        depth: 1,
        autonomyFor10: 400,
        autonomy: 400,
        link: "https://www.ecoumene.com/produit/semences/potageres/rutabaga-joan-bio/",
      },
      {
        name: "Sarriette",
        length: 20,
        width: 30,
        staggeredWidth: 29,
        depth: 0,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/herbacees/sarriette-ancienne-dacadie-bio/",
      },
      {
        name: "Sauge",
        length: 30,
        width: 45,
        staggeredWidth: 43,
        depth: 0.5,
        autonomyFor10: 4,
        autonomy: 4,
        link: "https://www.ecoumene.com/produit/semences/herbacees/sauge-officinale-bio/",
      },
      {
        name: "Scorsonère",
        length: 20,
        width: 20,
        staggeredWidth: 18,
        depth: 1,
        autonomyFor10: 12,
        autonomy: 12,
        link: "https://www.ecoumene.com/produit/semences/herbacees/scorsonere-hoffmans-schwarze-bio/",
      },
      {
        name: "Soja edamame",
        length: 30,
        width: 60,
        staggeredWidth: 59,
        depth: 2,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/soja-edamame-envy-bio/",
      },
      {
        name: "Souchet",
        length: 45,
        width: 90,
        staggeredWidth: 88,
        depth: 2,
        autonomyFor10: 48,
        autonomy: 48,
        link: "https://www.ecoumene.com/produit/semences/potageres/souchet-comestible-bio/",
      },
      {
        name: "Souci",
        length: 30,
        width: 45,
        staggeredWidth: 43,
        depth: 0.5,
        autonomyFor10: 24,
        autonomy: 24,
        link: "https://www.ecoumene.com/produit/semences/herbacees/souci-en-melange-bio/",
      },
      {
        name: "Thym",
        length: 30,
        width: 30,
        staggeredWidth: 26,
        depth: 0,
        autonomyFor10: 12,
        autonomy: 12,
        link: "https://www.ecoumene.com/produit/semences/herbacees/thym-serpolet-bio/",
      },
      {
        name: "Tomate",
        length: 30,
        width: 40,
        staggeredWidth: 38,
        depth: 0.5,
        autonomyFor10: 54,
        autonomy: 54,
        link: "https://www.ecoumene.com/produit/semences/potageres/tomate/type-beefsteak/tomate-meme-de-beauce-bio/",
      },
      {
        name: "Tomate cerise",
        length: 30,
        width: 40,
        staggeredWidth: 38,
        depth: 0.5,
        autonomyFor10: 0,
        autonomy: 0,
        link: "https://www.ecoumene.com/produit/semences/potageres/tomate/type-cerise/tomate-petit-moineau-bio/",
      },
      {
        name: "Tomate italienne",
        length: 30,
        width: 40,
        staggeredWidth: 38,
        depth: 0.5,
        autonomyFor10: 18,
        autonomy: 18,
        link: "https://www.ecoumene.com/produit/semences/potageres/tomate/type-italienne/tomate-amish-bio/",
      },
      {
        name: "Topinambour",
        length: 60,
        width: 75,
        staggeredWidth: 69,
        depth: 10,
        autonomyFor10: 48,
        autonomy: 48,
        link: "https://www.ecoumene.com/produit/semences/herbacees/topinambour-fuseau-rouge-bio/",
      },
      {
        name: "Tournesol",
        length: 40,
        width: 60,
        staggeredWidth: 57,
        depth: 2,
        autonomyFor10: 48,
        autonomy: 48,
        link: "https://www.ecoumene.com/produit/semences/herbacees/tournesol-arikara-bio/",
      },
    ],
  },
  reducers: {
    convertPlantAutonomies: (state, { payload }) => {
      state.autonomy = payload;
      if (isNaN(state.autonomy)) {
        state.autonomy = 10;
      }

      state.plants = state.plants.map(
        ({ autonomy, autonomyFor10, ...rest }) => ({
          ...rest,
          autonomyFor10,
          autonomy: Math.round((autonomyFor10 / 10) * state.autonomy),
        })
      );
    },
  },
});

export const { convertPlantAutonomies } = dataSlice.actions;

export default dataSlice.reducer;
